### ISSUE TITLE
URL en Parametro

### ISSUE THREAD

**Issue by softwaredelcentro** [softwaredelcentro/sobio-playground#1]
Permitir que la url de la API pueda ser pasada como parametro en la URL

Ejemplo https://softwaredelcentro.github.io/sobio-playground/index.html?apiurl=https://xxxxyyy

**Comment by AlexanderEberle** [comment]
Se puede realizar esto de la siguiente manera:

https://softwaredelcentro.github.io/sobio-playground#api=http://xxxx.yyy/zzzz

Saludos.
