### ISSUE TITLE
FavIcon

### ISSUE THREAD

**Issue by softwaredelcentro** [softwaredelcentro/sobio-playground#3]
Usar el icono https://send.firefox.com/download/4cd590bc92d19d27/#HAiNCtOKH_oY7KSS23uWDg

**Comment by AlexanderEberle** [comment]
Corregido con el commit [e80e342](https://github.com/softwaredelcentro/sobio-playground/commit/32c90ece32f33a02360444d7566a682d5e80e342)

Saludos,
