### ISSUE TITLE
Thumbnail en extraccion

### ISSUE THREAD

**Issue by softwaredelcentro** [softwaredelcentro/sobio-playground#6]
En extraccion de imagen y video, mostrar el thumbnail (2do item) en el tab "Response Processed". Actualmente se está mostrando el campo imagen de la respuesta, pero en imágenes rotadas/apaisdas se ve mal. Debería mostrar el campo thumbnail de faceProperties.

**Comment by AlexanderEberle** [comment]
Resuelto.
